point_cloud_topic: "/point_cloud"
map_frame_id: "/sensor_init"
robot_base_frame_id: "/base_link"
robot_pose_with_covariance_topic: "/odometry_for_elevation_map"
robot_pose_cache_size: 10
track_point_frame_id: "/base_link"
sensor_frame_id: "/lidar"
track_point_x: 0.0
track_point_y: 0.0
track_point_z: 0.0
time_tolerance: 10.0
